fx_version 'cerulean'
game 'gta5'
lua54 'yes'

ui_page 'noc/web/index.html'

author 'gnsh'
description 'Standalone server-authoritative GSM and telecom infrastructure'
version '0.1.0'

shared_scripts {
    'config/default.lua',
    'config/towers.lua',
    'shared/config.lua',
    'shared/constants.lua',
    'shared/enums.lua',
    'shared/technologies.lua',
    'shared/carriers.lua',
    'shared/feature_flags.lua',
    'shared/utils.lua',
    'shared/service_policy.lua',
    'locales/en.lua',
    'locales/tr.lua',
}

server_scripts {
    'server/towers/sectors.lua',
    'server/towers/validation.lua',
    'server/towers/state.lua',
    'server/towers/registry.lua',
    'server/carriers/registry.lua',
    'server/towers/spatial_index.lua',
    'server/network/signal.lua',
    'server/network/coverage.lua',
    'server/network/technology_selection.lua',
    'server/carriers/selection.lua',
    'server/network/selection.lua',
    'server/network/capacity.lua',
    'server/network/services.lua',
    'server/network/connections.lua',
    'server/backhaul/nodes.lua',
    'server/backhaul/links.lua',
    'server/backhaul/regions.lua',
    'server/backhaul/graph.lua',
    'server/backhaul/routing.lua',
    'server/api.lua',
    'server/failures/types.lua',
    'server/failures/engine.lua',
    'server/backhaul/outage_propagation.lua',
    'server/failures/scheduler.lua',
    'server/incidents/severity.lua',
    'server/incidents/tickets.lua',
    'server/incidents/manager.lua',
    'bridges/core/capabilities.lua',
    'bridges/core/contracts.lua',
    'bridges/core/lifecycle.lua',
    'bridges/core/health.lua',
    'bridges/core/registry.lua',
    'bridges/core/manager.lua',
    'bridges/phones/core/contract.lua',
    'bridges/phones/core/manager.lua',
    'bridges/phones/generic.lua',
    'bridges/phones/lbphone/server.lua',
    'bridges/phones/npwd/server.lua',
    'bridges/phones/qs/server.lua',
    'bridges/phones/custom.lua',
    'bridges/frameworks/standalone.lua',
    'bridges/frameworks/qb.lua',
    'bridges/frameworks/qbox.lua',
    'bridges/frameworks/esx.lua',
    'bridges/frameworks/custom.lua',
    'bridges/inventory/generic.lua',
    'bridges/inventory/ox.lua',
    'bridges/inventory/qb.lua',
    'bridges/inventory/qs.lua',
    'bridges/inventory/standalone.lua',
    'bridges/inventory/custom.lua',
    'bridges/target/generic.lua',
    'bridges/target/ox.lua',
    'bridges/target/qb.lua',
    'bridges/target/native.lua',
    'bridges/target/custom.lua',
    'bridges/dispatch/generic.lua',
    'bridges/notify/native.lua',
    'bridges/notify/ox.lua',
    'bridges/notify/framework.lua',
    'bridges/progress/native.lua',
    'bridges/progress/ox.lua',
    'bridges/dispatch/native.lua',
    'bridges/dispatch/custom.lua',
    'server/security/validation.lua',
    'server/security/rate_limit.lua',
    'server/maintenance/sessions.lua',
    'server/maintenance/components.lua',
    'server/maintenance/work_orders.lua',
    'server/maintenance/diagnostics.lua',
    'server/maintenance/repairs.lua',
    'server/maintenance/workflow.lua',
    'server/sabotage.lua',
    'server/jammers.lua',
    'server/statistics.lua',
    'noc/server.lua',
    'noc/server_stream.lua',
    'server/logging.lua',
    'server/persistence/serializers.lua',
    'server/persistence/adapters/memory.lua',
    'server/persistence/adapters/oxmysql.lua',
    'server/persistence/repository.lua',
    'server/persistence/migrations.lua',
    'server/persistence/facade.lua',
    'server/security/txadmin.lua',
    'server/security/permissions.lua',
    'server/security/audit.lua',
    'server/debug.lua',
    'server/bootstrap.lua',
}

client_scripts {
    'bridges/target/generic.lua',
    'bridges/target/ox.lua',
    'bridges/target/qb.lua',
    'bridges/target/native.lua',
    'bridges/target/custom.lua',
    'bridges/phones/core/contract.lua',
    'bridges/phones/core/manager.lua',
    'bridges/phones/generic.lua',
    'bridges/phones/lbphone/client.lua',
    'bridges/phones/npwd/client.lua',
    'bridges/phones/qs/client.lua',
    'bridges/phones/custom.lua',
    'bridges/notify/native.lua',
    'bridges/notify/ox.lua',
    'bridges/notify/framework.lua',
    'bridges/progress/native.lua',
    'bridges/progress/ox.lua',
    'client/bootstrap.lua',
    'client/environment.lua',
    'client/state.lua',
    'client/debug.lua',
    'client/handover.lua',
    'client/nui.lua',
    'client/technician.lua',
    'client/interactions.lua',
    'noc/client.lua',
    'noc/client_stream.lua',
}

files {
    'noc/web/index.html',
}
