-- Production logical backhaul topology.
--
-- These are network nodes and links, not GTA entities. Tower coordinates and
-- optional visual props remain independent from this logical transport graph.
-- Every production tower is mapped to an aggregation node and a deployment
-- region so routing, regional outages, and NOC metadata stay authoritative.
Config.Backhaul = {
    routeCacheTtlMs = 5000,
    maxRouteCacheEntries = 256,
    maxRecomputeNodes = 128,
    maxPathHops = 16,
    maxRegionalTowers = 128,

    coreNodes = {
        'CORE-BLAINE-01',
        'CORE-LOS-SANTOS-01',
    },

    towerNodes = {
        ['BC-CHUMASH-01'] = 'AGG-BLAINE-WEST-01',
        ['BC-GRAPESEED-01'] = 'AGG-BLAINE-EAST-01',
        ['BC-HARMONY-01'] = 'AGG-BLAINE-CENTRAL-01',
        ['BC-PALETO-01'] = 'AGG-BLAINE-EAST-01',
        ['BC-PALETO-02'] = 'AGG-BLAINE-EAST-01',
        ['BC-SANDY-01'] = 'AGG-BLAINE-CENTRAL-01',
        ['BC-SANDY-02'] = 'AGG-BLAINE-CENTRAL-01',
        ['BC-ZANCUDO-01'] = 'AGG-BLAINE-WEST-01',
        ['HW-GOH-01'] = 'AGG-BLAINE-WEST-01',
        ['HW-GOH-02'] = 'AGG-BLAINE-WEST-01',
        ['HW-NORTH-01'] = 'AGG-BLAINE-EAST-01',
        ['HW-PALOMINO-01'] = 'AGG-HIGHWAY-SOUTH-01',
        ['HW-R68-01'] = 'AGG-BLAINE-CENTRAL-01',
        ['HW-SENORA-01'] = 'AGG-BLAINE-EAST-01',
        ['HW-SENORA-02'] = 'AGG-BLAINE-EAST-01',
        ['HW-SANDY-EAST-01'] = 'AGG-BLAINE-CENTRAL-01',
        ['HW-SENORA-CORRIDOR-01'] = 'AGG-BLAINE-EAST-01',
        ['HW-DAVIS-FREEWAY-01'] = 'AGG-LS-01',
        ['LS-CYPRESS-01'] = 'AGG-LS-01',
        ['LS-DAVIS-01'] = 'AGG-LS-01',
        ['LS-DELPERRO-01'] = 'AGG-LS-01',
        ['LS-DOWNTOWN-01'] = 'AGG-LS-01',
        ['LS-EAST-01'] = 'AGG-LS-01',
        ['LS-LAMESA-01'] = 'AGG-LS-01',
        ['LS-LAPUERTA-01'] = 'AGG-LS-01',
        ['LS-LSIA-01'] = 'AGG-LS-01',
        ['LS-MIRRORPARK-01'] = 'AGG-LS-01',
        ['LS-MISSIONROW-01'] = 'AGG-LS-01',
        ['LS-MURRIETA-01'] = 'AGG-LS-01',
        ['LS-PORT-01'] = 'AGG-LS-01',
        ['LS-RICHMAN-01'] = 'AGG-LS-01',
        ['LS-ROCKFORD-01'] = 'AGG-LS-01',
        ['LS-VESPUCCI-01'] = 'AGG-LS-01',
        ['LS-VINEWOOD-01'] = 'AGG-LS-01',
        ['RM-CHILIAD-CABLE-01'] = 'AGG-REMOTE-01',
        ['CUSTOM-LARGE-01'] = 'AGG-REMOTE-01',
        ['CUSTOM-MEDIUM-01'] = 'AGG-REMOTE-01',
        ['CUSTOM-MEDIUM-02'] = 'AGG-REMOTE-01',
        ['CUSTOM-HIGHWAY-01'] = 'AGG-HIGHWAY-SOUTH-01',
        ['CUSTOM-MEDIUM-03'] = 'AGG-BLAINE-EAST-01',
    },

    regions = {
        {
            id = 'REGION_LOS_SANTOS',
            popNode = 'POP-LS-A',
            towerIds = {
                'HW-DAVIS-FREEWAY-01',
                'LS-CYPRESS-01', 'LS-DAVIS-01', 'LS-DELPERRO-01',
                'LS-DOWNTOWN-01', 'LS-EAST-01', 'LS-LAMESA-01',
                'LS-LAPUERTA-01', 'LS-LSIA-01', 'LS-MIRRORPARK-01',
                'LS-MISSIONROW-01', 'LS-MURRIETA-01', 'LS-PORT-01',
                'LS-RICHMAN-01', 'LS-ROCKFORD-01', 'LS-VESPUCCI-01',
                'LS-VINEWOOD-01',
            },
            nodeIds = { 'AGG-LS-01', 'POP-LS-B' },
            coreNodes = { 'CORE-BLAINE-01', 'CORE-LOS-SANTOS-01' },
            metadata = { serviceClass = 'METRO' },
        },
        {
            id = 'REGION_BLAINE_WEST',
            popNode = 'POP-BLAINE-WEST-A',
            towerIds = {
                'BC-CHUMASH-01', 'BC-ZANCUDO-01',
                'HW-GOH-01', 'HW-GOH-02',
            },
            nodeIds = { 'AGG-BLAINE-WEST-01', 'POP-BLAINE-WEST-B' },
            coreNodes = { 'CORE-BLAINE-01', 'CORE-LOS-SANTOS-01' },
            metadata = { serviceClass = 'TOWN_AND_HIGHWAY' },
        },
        {
            id = 'REGION_BLAINE_CENTRAL',
            popNode = 'POP-BLAINE-CENTRAL-A',
            towerIds = {
                'BC-HARMONY-01', 'BC-SANDY-01', 'BC-SANDY-02',
                'HW-R68-01', 'HW-SANDY-EAST-01',
            },
            nodeIds = { 'AGG-BLAINE-CENTRAL-01', 'POP-BLAINE-CENTRAL-B' },
            coreNodes = { 'CORE-BLAINE-01', 'CORE-LOS-SANTOS-01' },
            metadata = { serviceClass = 'TOWN_AND_HIGHWAY' },
        },
        {
            id = 'REGION_BLAINE_EAST',
            popNode = 'POP-BLAINE-EAST-A',
            towerIds = {
                'BC-GRAPESEED-01', 'BC-PALETO-01', 'BC-PALETO-02',
                'HW-NORTH-01', 'HW-SENORA-01', 'HW-SENORA-02',
                'HW-SENORA-CORRIDOR-01', 'CUSTOM-MEDIUM-03',
            },
            nodeIds = { 'AGG-BLAINE-EAST-01', 'POP-BLAINE-EAST-B' },
            coreNodes = { 'CORE-BLAINE-01', 'CORE-LOS-SANTOS-01' },
            metadata = { serviceClass = 'TOWN_AND_HIGHWAY' },
        },
        {
            id = 'REGION_REMOTE_WILDERNESS',
            popNode = 'POP-REMOTE-A',
            towerIds = {
                'RM-CHILIAD-CABLE-01', 'CUSTOM-LARGE-01',
                'CUSTOM-MEDIUM-01', 'CUSTOM-MEDIUM-02',
            },
            nodeIds = { 'AGG-REMOTE-01', 'POP-REMOTE-B' },
            coreNodes = { 'CORE-BLAINE-01', 'CORE-LOS-SANTOS-01' },
            metadata = { serviceClass = 'RURAL_AND_WILDERNESS' },
        },
        {
            id = 'REGION_HIGHWAY_SOUTH',
            popNode = 'POP-HIGHWAY-SOUTH-A',
            towerIds = { 'HW-PALOMINO-01', 'CUSTOM-HIGHWAY-01' },
            nodeIds = { 'AGG-HIGHWAY-SOUTH-01', 'POP-HIGHWAY-SOUTH-B' },
            coreNodes = { 'CORE-BLAINE-01', 'CORE-LOS-SANTOS-01' },
            metadata = { serviceClass = 'HIGHWAY' },
        },
    },

    nodes = {
        { id = 'AGG-LS-01', type = 'AGGREGATION', metadata = { regionId = 'REGION_LOS_SANTOS' } },
        { id = 'AGG-BLAINE-WEST-01', type = 'AGGREGATION', metadata = { regionId = 'REGION_BLAINE_WEST' } },
        { id = 'AGG-BLAINE-CENTRAL-01', type = 'AGGREGATION', metadata = { regionId = 'REGION_BLAINE_CENTRAL' } },
        { id = 'AGG-BLAINE-EAST-01', type = 'AGGREGATION', metadata = { regionId = 'REGION_BLAINE_EAST' } },
        { id = 'AGG-REMOTE-01', type = 'AGGREGATION', metadata = { regionId = 'REGION_REMOTE_WILDERNESS' } },
        { id = 'AGG-HIGHWAY-SOUTH-01', type = 'AGGREGATION', metadata = { regionId = 'REGION_HIGHWAY_SOUTH' } },

        { id = 'POP-LS-A', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_LOS_SANTOS', path = 'primary' } },
        { id = 'POP-LS-B', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_LOS_SANTOS', path = 'backup' } },
        { id = 'POP-BLAINE-WEST-A', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_BLAINE_WEST', path = 'primary' } },
        { id = 'POP-BLAINE-WEST-B', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_BLAINE_WEST', path = 'backup' } },
        { id = 'POP-BLAINE-CENTRAL-A', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_BLAINE_CENTRAL', path = 'primary' } },
        { id = 'POP-BLAINE-CENTRAL-B', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_BLAINE_CENTRAL', path = 'backup' } },
        { id = 'POP-BLAINE-EAST-A', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_BLAINE_EAST', path = 'primary' } },
        { id = 'POP-BLAINE-EAST-B', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_BLAINE_EAST', path = 'backup' } },
        { id = 'POP-REMOTE-A', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_REMOTE_WILDERNESS', path = 'primary' } },
        { id = 'POP-REMOTE-B', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_REMOTE_WILDERNESS', path = 'backup' } },
        { id = 'POP-HIGHWAY-SOUTH-A', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_HIGHWAY_SOUTH', path = 'primary' } },
        { id = 'POP-HIGHWAY-SOUTH-B', type = 'REGIONAL_POP', metadata = { regionId = 'REGION_HIGHWAY_SOUTH', path = 'backup' } },

        { id = 'CORE-BLAINE-01', type = 'CORE', metadata = { scope = 'statewide' } },
        { id = 'CORE-LOS-SANTOS-01', type = 'CORE', metadata = { scope = 'statewide' } },
    },

    links = {
        { id = 'BH-LS-POP-A', from = 'AGG-LS-01', to = 'POP-LS-A', type = 'FIBER', capacity = 1000 },
        { id = 'BH-LS-POP-B', from = 'AGG-LS-01', to = 'POP-LS-B', type = 'FIBER', capacity = 1000 },
        { id = 'BH-LS-A-BLAINE', from = 'POP-LS-A', to = 'CORE-BLAINE-01', type = 'FIBER', capacity = 2000 },
        { id = 'BH-LS-A-LOS', from = 'POP-LS-A', to = 'CORE-LOS-SANTOS-01', type = 'FIBER', capacity = 2000 },
        { id = 'BH-LS-B-BLAINE', from = 'POP-LS-B', to = 'CORE-BLAINE-01', type = 'FIBER', capacity = 2000 },
        { id = 'BH-LS-B-LOS', from = 'POP-LS-B', to = 'CORE-LOS-SANTOS-01', type = 'FIBER', capacity = 2000 },

        { id = 'BH-BW-POP-A', from = 'AGG-BLAINE-WEST-01', to = 'POP-BLAINE-WEST-A', type = 'FIBER', capacity = 750 },
        { id = 'BH-BW-POP-B', from = 'AGG-BLAINE-WEST-01', to = 'POP-BLAINE-WEST-B', type = 'FIBER', capacity = 750 },
        { id = 'BH-BW-A-BLAINE', from = 'POP-BLAINE-WEST-A', to = 'CORE-BLAINE-01', type = 'FIBER', capacity = 1500 },
        { id = 'BH-BW-A-LOS', from = 'POP-BLAINE-WEST-A', to = 'CORE-LOS-SANTOS-01', type = 'FIBER', capacity = 1500 },
        { id = 'BH-BW-B-BLAINE', from = 'POP-BLAINE-WEST-B', to = 'CORE-BLAINE-01', type = 'FIBER', capacity = 1500 },
        { id = 'BH-BW-B-LOS', from = 'POP-BLAINE-WEST-B', to = 'CORE-LOS-SANTOS-01', type = 'FIBER', capacity = 1500 },

        { id = 'BH-BC-POP-A', from = 'AGG-BLAINE-CENTRAL-01', to = 'POP-BLAINE-CENTRAL-A', type = 'FIBER', capacity = 750 },
        { id = 'BH-BC-POP-B', from = 'AGG-BLAINE-CENTRAL-01', to = 'POP-BLAINE-CENTRAL-B', type = 'FIBER', capacity = 750 },
        { id = 'BH-BC-A-BLAINE', from = 'POP-BLAINE-CENTRAL-A', to = 'CORE-BLAINE-01', type = 'FIBER', capacity = 1500 },
        { id = 'BH-BC-A-LOS', from = 'POP-BLAINE-CENTRAL-A', to = 'CORE-LOS-SANTOS-01', type = 'FIBER', capacity = 1500 },
        { id = 'BH-BC-B-BLAINE', from = 'POP-BLAINE-CENTRAL-B', to = 'CORE-BLAINE-01', type = 'FIBER', capacity = 1500 },
        { id = 'BH-BC-B-LOS', from = 'POP-BLAINE-CENTRAL-B', to = 'CORE-LOS-SANTOS-01', type = 'FIBER', capacity = 1500 },

        { id = 'BH-BE-POP-A', from = 'AGG-BLAINE-EAST-01', to = 'POP-BLAINE-EAST-A', type = 'FIBER', capacity = 750 },
        { id = 'BH-BE-POP-B', from = 'AGG-BLAINE-EAST-01', to = 'POP-BLAINE-EAST-B', type = 'FIBER', capacity = 750 },
        { id = 'BH-BE-A-BLAINE', from = 'POP-BLAINE-EAST-A', to = 'CORE-BLAINE-01', type = 'FIBER', capacity = 1500 },
        { id = 'BH-BE-A-LOS', from = 'POP-BLAINE-EAST-A', to = 'CORE-LOS-SANTOS-01', type = 'FIBER', capacity = 1500 },
        { id = 'BH-BE-B-BLAINE', from = 'POP-BLAINE-EAST-B', to = 'CORE-BLAINE-01', type = 'FIBER', capacity = 1500 },
        { id = 'BH-BE-B-LOS', from = 'POP-BLAINE-EAST-B', to = 'CORE-LOS-SANTOS-01', type = 'FIBER', capacity = 1500 },

        { id = 'BH-REMOTE-POP-A', from = 'AGG-REMOTE-01', to = 'POP-REMOTE-A', type = 'MICROWAVE', capacity = 250 },
        { id = 'BH-REMOTE-POP-B', from = 'AGG-REMOTE-01', to = 'POP-REMOTE-B', type = 'MICROWAVE', capacity = 250 },
        { id = 'BH-REMOTE-A-BLAINE', from = 'POP-REMOTE-A', to = 'CORE-BLAINE-01', type = 'MICROWAVE', capacity = 500 },
        { id = 'BH-REMOTE-A-LOS', from = 'POP-REMOTE-A', to = 'CORE-LOS-SANTOS-01', type = 'MICROWAVE', capacity = 500 },
        { id = 'BH-REMOTE-B-BLAINE', from = 'POP-REMOTE-B', to = 'CORE-BLAINE-01', type = 'MICROWAVE', capacity = 500 },
        { id = 'BH-REMOTE-B-LOS', from = 'POP-REMOTE-B', to = 'CORE-LOS-SANTOS-01', type = 'MICROWAVE', capacity = 500 },

        { id = 'BH-HWY-POP-A', from = 'AGG-HIGHWAY-SOUTH-01', to = 'POP-HIGHWAY-SOUTH-A', type = 'FIBER', capacity = 500 },
        { id = 'BH-HWY-POP-B', from = 'AGG-HIGHWAY-SOUTH-01', to = 'POP-HIGHWAY-SOUTH-B', type = 'FIBER', capacity = 500 },
        { id = 'BH-HWY-A-BLAINE', from = 'POP-HIGHWAY-SOUTH-A', to = 'CORE-BLAINE-01', type = 'FIBER', capacity = 1000 },
        { id = 'BH-HWY-A-LOS', from = 'POP-HIGHWAY-SOUTH-A', to = 'CORE-LOS-SANTOS-01', type = 'FIBER', capacity = 1000 },
        { id = 'BH-HWY-B-BLAINE', from = 'POP-HIGHWAY-SOUTH-B', to = 'CORE-BLAINE-01', type = 'FIBER', capacity = 1000 },
        { id = 'BH-HWY-B-LOS', from = 'POP-HIGHWAY-SOUTH-B', to = 'CORE-LOS-SANTOS-01', type = 'FIBER', capacity = 1000 },
    },
}
