-- Coordinate-free deployment catalog. The editor captures real FiveM positions
-- during a development session; this file is never authoritative tower topology.
Config.DeploymentSites = {
    {
        id = 'LS-LSIA-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_CORE',
        purpose = 'Los Santos International Airport metro coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-PORT-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_CORE',
        purpose = 'Port of Los Santos industrial metro coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-LAPUERTA-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_CORE',
        purpose = 'La Puerta metro coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-VESPUCCI-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_CORE',
        purpose = 'Vespucci and beachfront metro coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-DELPERRO-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_EDGE',
        purpose = 'Del Perro urban edge coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-ROCKFORD-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_EDGE',
        purpose = 'Rockford Hills urban edge coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-DOWNTOWN-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_CORE',
        purpose = 'Downtown Los Santos metro core coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-MISSIONROW-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_CORE',
        purpose = 'Mission Row metro core coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-DAVIS-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_EDGE',
        purpose = 'Davis urban edge coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-LAMESA-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_EDGE',
        purpose = 'La Mesa urban edge coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-CYPRESS-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_EDGE',
        purpose = 'Cypress Flats industrial edge coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-MURRIETA-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_EDGE',
        purpose = 'Murrieta Heights urban edge coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-VINEWOOD-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_EDGE',
        purpose = 'Vinewood urban edge coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-MIRRORPARK-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_EDGE',
        purpose = 'Mirror Park urban edge coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-RICHMAN-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_EDGE',
        purpose = 'Richman urban edge coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'LS-EAST-01',
        class = 'METRO_MACRO',
        coverageZone = 'METRO_EDGE',
        purpose = 'East Los Santos urban edge coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'BC-SANDY-01',
        class = 'TOWN_MACRO',
        coverageZone = 'TOWN',
        purpose = 'Sandy Shores west town coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'BC-SANDY-02',
        class = 'TOWN_MACRO',
        coverageZone = 'TOWN',
        purpose = 'Sandy Shores east town coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'BC-GRAPESEED-01',
        class = 'TOWN_MACRO',
        coverageZone = 'TOWN',
        purpose = 'Grapeseed town coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'BC-PALETO-01',
        class = 'TOWN_MACRO',
        coverageZone = 'TOWN',
        purpose = 'Paleto Bay west town coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'BC-PALETO-02',
        class = 'TOWN_MACRO',
        coverageZone = 'TOWN',
        purpose = 'Paleto Bay east town coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'BC-HARMONY-01',
        class = 'TOWN_MACRO',
        coverageZone = 'TOWN',
        purpose = 'Harmony town coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'BC-CHUMASH-01',
        class = 'TOWN_MACRO',
        coverageZone = 'TOWN',
        purpose = 'Chumash coastal town coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'BC-ZANCUDO-01',
        class = 'TOWN_MACRO',
        coverageZone = 'TOWN',
        purpose = 'Fort Zancudo access settlement coverage',
        technologies = { '4G', '5G' },
    },
    {
        id = 'HW-GOH-01',
        class = 'HIGHWAY_REPEATER',
        coverageZone = 'HIGHWAY',
        purpose = 'Great Ocean Highway south repeater',
        technologies = { '4G' },
    },
    {
        id = 'HW-GOH-02',
        class = 'HIGHWAY_REPEATER',
        coverageZone = 'HIGHWAY',
        purpose = 'Great Ocean Highway north repeater',
        technologies = { '4G' },
    },
    {
        id = 'HW-SENORA-01',
        class = 'HIGHWAY_REPEATER',
        coverageZone = 'HIGHWAY',
        purpose = 'Senora Freeway south repeater',
        technologies = { '4G' },
    },
    {
        id = 'HW-SENORA-02',
        class = 'HIGHWAY_REPEATER',
        coverageZone = 'HIGHWAY',
        purpose = 'Senora Freeway north repeater',
        technologies = { '4G' },
    },
    {
        id = 'HW-R68-01',
        class = 'HIGHWAY_REPEATER',
        coverageZone = 'HIGHWAY',
        purpose = 'Route 68 highway repeater',
        technologies = { '4G' },
    },
    {
        id = 'HW-PALOMINO-01',
        class = 'HIGHWAY_REPEATER',
        coverageZone = 'HIGHWAY',
        purpose = 'Palomino Freeway east repeater',
        technologies = { '4G' },
    },
    {
        id = 'HW-NORTH-01',
        class = 'HIGHWAY_REPEATER',
        coverageZone = 'HIGHWAY',
        purpose = 'Northern highway transition repeater',
        technologies = { '4G' },
    },
    {
        id = 'HW-SANDY-EAST-01',
        class = 'HIGHWAY_REPEATER',
        coverageZone = 'HIGHWAY',
        purpose = 'TP-07 verified Sandy eastern corridor highway gap coverage',
        technologies = { '4G' },
    },
    {
        id = 'HW-SENORA-CORRIDOR-01',
        class = 'HIGHWAY_REPEATER',
        coverageZone = 'HIGHWAY',
        purpose = 'TP-07 verified Sandy-to-Senora corridor highway gap coverage',
        technologies = { '4G' },
    },
    {
        id = 'HW-DAVIS-FREEWAY-01',
        class = 'HIGHWAY_REPEATER',
        coverageZone = 'HIGHWAY',
        purpose = 'TP-07 verified La Puerta-to-Davis freeway gap coverage',
        technologies = { '4G' },
    },
    {
        id = 'RM-CHILIAD-CABLE-01',
        class = 'REMOTE_REPEATER',
        coverageZone = 'WILDERNESS',
        purpose = 'Mount Chiliad cable access remote repeater',
        technologies = { '4G' },
    },
}
