Constants = {
    ResourceName = 'gnsh-telecom',
    ApiVersion = '1.0',
    PersistenceSchemaVersion = 2,
    LogEvent = {
        CONFIG_OK = 'CONFIG_OK',
        CONFIG_INVALID = 'CONFIG_INVALID',
        RESOURCE_STARTED = 'RESOURCE_STARTED',
        RESOURCE_STOPPED = 'RESOURCE_STOPPED',
    },
    Events = {
        POSITION_UPDATE = 'gnsh-telecom:server:updatePosition',
        CONNECTION_STATE = 'gnsh-telecom:client:connectionState',
        DEBUG_OVERLAY = 'gnsh-telecom:client:debugOverlay',
        DEBUG_MESSAGE = 'gnsh-telecom:client:debugMessage',
        INCIDENT_REQUEST = 'gnsh-telecom:server:incidentRequest',
        INCIDENT_STATE = 'gnsh-telecom:client:incidentState',
        MAINTENANCE_REQUEST = 'gnsh-telecom:server:maintenanceRequest',
        MAINTENANCE_TARGET_REQUEST = 'gnsh-telecom:server:maintenanceTargetRequest',
        MAINTENANCE_STATE = 'gnsh-telecom:client:maintenanceState',
        NOC_REQUEST = 'gnsh-telecom:server:nocRequest',
        NOC_STATE = 'gnsh-telecom:client:nocState',
        NOC_DELTA = 'gnsh-telecom:client:nocDelta',
        NOC_RECONCILE = 'gnsh-telecom:server:nocReconcile',
        NOC_UNSUBSCRIBE = 'gnsh-telecom:server:nocUnsubscribe',
        NOC_CLOSE = 'gnsh-telecom:client:nocClose',
        JAMMER_REQUEST = 'gnsh-telecom:server:jammerRequest',
        JAMMER_STATE = 'gnsh-telecom:client:jammerState',
        SABOTAGE_REQUEST = 'gnsh-telecom:server:sabotageRequest',
        SABOTAGE_STATE = 'gnsh-telecom:client:sabotageState',
        DEPLOYMENT_EDITOR_TOGGLE = 'gnsh-telecom:client:deploymentEditorToggle',
        DEPLOYMENT_EDITOR_PREVIEW = 'gnsh-telecom:client:deploymentEditorPreview',
        DEPLOYMENT_EDITOR_CLEAR = 'gnsh-telecom:client:deploymentEditorClear',
        DEPLOYMENT_EDITOR_DRAFTS = 'gnsh-telecom:client:deploymentEditorDrafts',
        DEPLOYMENT_EDITOR_DRAFTS_CLEAR = 'gnsh-telecom:client:deploymentEditorDraftsClear',
        DEPLOYMENT_CAPTURE_RESULT = 'gnsh-telecom:client:deploymentCaptureResult',
    },
    SupportEvents = {
        NOTIFY = 'gnsh-telecom:client:notify',
        PROGRESS_START = 'gnsh-telecom:client:progressStart',
        DISPATCH_ALERT = 'gnsh-telecom:server:dispatchAlert',
    },
    ApiEvents = {
        CONNECTION_CHANGED = 'gnsh-telecom:connectionChanged',
        SIGNAL_CHANGED = 'gnsh-telecom:signalChanged',
        SIGNAL_LEVEL_CHANGED = 'gnsh-telecom:signalLevelChanged',
        TOWER_CHANGED = 'gnsh-telecom:towerChanged',
        SECTOR_CHANGED = 'gnsh-telecom:sectorChanged',
        NETWORK_TYPE_CHANGED = 'gnsh-telecom:networkTypeChanged',
        SERVICE_CHANGED = 'gnsh-telecom:serviceChanged',
        INCIDENT_CHANGED = 'gnsh-telecom:incidentChanged',
        HANDOVER = 'gnsh-telecom:handover',
        BACKHAUL_CHANGED = 'gnsh-telecom:backhaulChanged',
    },
}
