Enums = {
    TowerState = {
        OPERATIONAL = 'OPERATIONAL',
        DEGRADED = 'DEGRADED',
        MAINTENANCE = 'MAINTENANCE',
        OFFLINE = 'OFFLINE',
        DESTROYED = 'DESTROYED',
    },
    BackhaulState = {
        ONLINE = 'ONLINE',
        DEGRADED = 'DEGRADED',
        OFFLINE = 'OFFLINE',
    },
    SignalLevel = {
        EXCELLENT = 'EXCELLENT',
        GOOD = 'GOOD',
        NORMAL = 'NORMAL',
        WEAK = 'WEAK',
        VERY_WEAK = 'VERY_WEAK',
        NO_SERVICE = 'NO_SERVICE',
    },
    CongestionState = {
        NORMAL = 'NORMAL',
        BUSY = 'BUSY',
        CONGESTED = 'CONGESTED',
        CRITICAL = 'CRITICAL',
        OVERLOADED = 'OVERLOADED',
    },
    DataPerformance = {
        NORMAL = 'NORMAL',
        DEGRADED = 'DEGRADED',
        SLOW = 'SLOW',
        VERY_SLOW = 'VERY_SLOW',
        UNAVAILABLE = 'UNAVAILABLE',
    },
    Service = {
        VOICE = 'VOICE',
        SMS = 'SMS',
        DATA = 'DATA',
        GPS = 'GPS',
        EMERGENCY = 'EMERGENCY',
    },
    IncidentState = {
        OPEN = 'OPEN',
        ACKNOWLEDGED = 'ACKNOWLEDGED',
        ASSIGNED = 'ASSIGNED',
        ON_ROUTE = 'ON_ROUTE',
        DIAGNOSING = 'DIAGNOSING',
        REPAIRING = 'REPAIRING',
        VERIFYING = 'VERIFYING',
        RESOLVED = 'RESOLVED',
        CLOSED = 'CLOSED',
    },
    WorkOrderState = {
        OFFERED = 'OFFERED',
        ACCEPTED = 'ACCEPTED',
        EN_ROUTE = 'EN_ROUTE',
        ON_SITE = 'ON_SITE',
        DIAGNOSING = 'DIAGNOSING',
        READY_FOR_REPAIR = 'READY_FOR_REPAIR',
        REPAIRING = 'REPAIRING',
        VERIFYING = 'VERIFYING',
        COMPLETED = 'COMPLETED',
        CANCELLED = 'CANCELLED',
    },
    IncidentSeverity = {
        LOW = 'LOW',
        MEDIUM = 'MEDIUM',
        HIGH = 'HIGH',
        CRITICAL = 'CRITICAL',
    },
    BackhaulNodeState = {
        ONLINE = 'ONLINE',
        OFFLINE = 'OFFLINE',
    },
    BackhaulNodeType = {
        TOWER = 'TOWER',
        AGGREGATION = 'AGGREGATION',
        REGIONAL_POP = 'REGIONAL_POP',
        CORE = 'CORE',
    },
    LinkState = {
        ONLINE = 'ONLINE',
        DEGRADED = 'DEGRADED',
        OFFLINE = 'OFFLINE',
    },
}
